[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.13.3"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.13.4"

[prune]
  go-tests = true
  unused-packages = true
